### ISSUE TITLE
Issue with servo when playing melody

### ISSUE THREAD

**Issue by Make-It-Racing** [fabianoriccardi/melody-player#1]
Hi,

Thank you for the library!
I found an issue, when a sevo is connected and melody is played, the servo goes crazy at the time of melody play.
Is there something that can be done?

Thank you

**Comment by fabianoriccardi** [comment]
Hi, sorry for the late reply. Which board are you using? ESP8266 or ESP32?

**Comment by Make-It-Racing** [comment]
Hi, ESP32
I found somewhere that there is an optional channels parameter, so I  changed the channel and it worked!
MelodyPlayer player(buzzerPin,6);

**Comment by fabianoriccardi** [comment]
I will insert it in the readme!

**Comment by Make-It-Racing** [comment]
Thanks,
By the way would you consider to add your library to Arduino IDE library manager?
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

I am working on a tutorial that will mention your library and it would be great if people would be able to just simply use it from within the IDE.

Thanks again for your work!

**Comment by fabianoriccardi** [comment]
Yeah, my intention was that, but in this period I had focused on other my libraries... However, I think that in a few days it will come to the turn of this! 

May you give me the link to your tutorial when ready?

**Comment by Make-It-Racing** [comment]
Sure, basically it is a robot based on ESP32 with a passive buzzer.
Will share the link when ready!

**Comment by fabianoriccardi** [comment]
[Request done](https://github.com/arduino/Arduino/issues/10318), I think it will be added in the next week

**Comment by Make-It-Racing** [comment]
Amazing! Thank you very much!
